# Generated by Django 4.2.11 on 2024-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('actions_and_solutions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ka_number', models.IntegerField()),
                ('service', models.CharField(default=' ', max_length=355)),
                ('configuration_item', models.CharField(default=' ', max_length=355)),
                ('ticket_type', models.CharField(default=' ', max_length=455)),
                ('subject', models.CharField(default=' ', max_length=255)),
                ('description', models.TextField(default=' ')),
                ('actions_and_solutions', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ka_number', models.IntegerField()),
                ('ka_title', models.CharField(default=' ', max_length=255)),
                ('service', models.CharField(default=' ', max_length=355)),
                ('configuration_item', models.CharField(default=' ', max_length=355)),
                ('ticket_type', models.CharField(default=' ', max_length=455)),
                ('actions', models.ManyToManyField(related_name='tickets', to='template_updater.action')),
                ('tags', models.ManyToManyField(related_name='tickets', to='template_updater.tag')),
            ],
        ),
    ]
