# Generated by Django 4.2.11 on 2024-05-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_updater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedupdate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
