# Generated by Django 5.0.4 on 2024-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_updater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default=0, max_length=455),
            preserve_default=False,
        ),
    ]
