# Generated by Django 4.2.11 on 2024-04-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_updater', '0003_suggestedupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedupdate',
            name='ka_title',
        ),
    ]
