# Generated by Django 4.2.11 on 2024-05-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_updater', '0004_remove_suggestedupdate_ka_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedupdate',
            name='actions_and_solutions',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='suggestedupdate',
            name='configuration_item',
            field=models.CharField(default=' ', max_length=355),
        ),
        migrations.AlterField(
            model_name='suggestedupdate',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='suggestedupdate',
            name='service',
            field=models.CharField(default=' ', max_length=355),
        ),
        migrations.AlterField(
            model_name='suggestedupdate',
            name='subject',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='suggestedupdate',
            name='ticket_type',
            field=models.CharField(default=' ', max_length=455),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='configuration_item',
            field=models.CharField(default=' ', max_length=355),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ka_title',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(default=' ', max_length=355),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(default=' ', max_length=455),
        ),
    ]
